from colorama import Back

INFO_RIGHT = 10
INFO_DOWN = 10

MIN_HEIGHT = 22
MIN_WIDTH = 70

TIME_BEFORE_BRICKS_DESCEND=20

TIME_GAP_BETWEEN_CONSECUTIVE_SHOTS=0.25

TIME_BETWEEN_BOMBS=10

TOT_LIVES=20
TOT_LEVELS=3
TOT_TIME=60000
SCORE_BRICK_DESTROYED=[0,1,2,3,4,5]
SCORE_POWERUP_PICKED=20
SCORE_LIFE_BONUS=20

POWERUP_PROBABILITY=0.3

UFO_TOTAL_HEALTH=10

KILLING_BOSS_SCORE=1000

FIRST_THRESHOLD=0.7
SECOND_THRESHOLD=0.4

DEFAULT_PADDLE_LEN=15
MAX_PADDLE_LEN=DEFAULT_PADDLE_LEN+8
MIN_PADDLE_LEN=DEFAULT_PADDLE_LEN-8

BRICKS_BGCOLORS=["",Back.GREEN,Back.YELLOW,Back.BLUE,Back.WHITE,Back.CYAN]

POWERUP_DURATION=10

BG_COLOR = Back.BLACK
DETAILS_BG_COLOR=Back.RED
